feat/first-stage-of-refactor (#117)
* feat/first-stage-of-refactor

* feat/tests-part-one

* eslint and prettier + formatted files

* Update build_privmx_endpoint

* snapshot

* fix/added-cpp-dependencies-to-ignore

* feat/refactor-adjustments

* fix/test-pipeline-fix

* fix/pipeline-script-adjustments-for-ci

* ci test

* fix/test-adjustments-and-ci-test

* fix/fixtures-adjustments

* test/ci-test

* ci-test

* ci-test

* ci-test-on-ubuntu-latest

* Add clang format and clang tidy (#121)

* fix/ci-fix

* fix/imports-fix

* snapshot

* adjustments-to-devel-merge

* chore: build and packaging adjustments

* fix/test-path

* feat: add audioLevel monitoring proof-of-concept and fix/update build process

* fix: linter issues

* feat: audio level detection

* chore/gmp-update-and-code-cleanup

* chore: bump version number

---------

Co-authored-by: Paweł Aniszewski <paniszewski@simplito.com>
Co-authored-by: Klaudia O <62263707+Loxx-KO@users.noreply.github.com>
Co-authored-by: Kamil Zuranski <zuranski83@gmail.com>

diff --git a/scripts/build_pson b/scripts/build_pson
--- a/scripts/build_pson
+++ b/scripts/build_pson
@@ -34,24 +34,50 @@ else
 fi
 
 
-cd "$PSON_DIR"
-
-# apply config patches for emscripte
+echo "Checking checksum: $PSON_DIR ..."
 set +e
-patch_out=$(patch --forward -d "$PSON_DIR" -p1 -i "$BASE_DIR/patches/pson-cpp.patch")
-status=$?
-if [ $status -eq 1 ]; then
-    if [[ $patch_out == *"FAILED"* ]]; then
-        echo "Patching PSON FAILED"; exit -1;
-    fi
-fi
+$SCRIPT_PATH/check_dir_checksum "$PSON_DIR"
+RESULT=$?
 set -e
+case "$RESULT" in
+    0)
+        echo "No changes - skipping build"
+        ;;
+    1)
+        echo "changes - rebuild..."
+        cd "$PSON_DIR"
 
-if [ ! -d "./build-emscripten" ]; then
-    mkdir -p build-emscripten && cd build-emscripten
-    emcmake cmake .. -D CMAKE_BUILD_TYPE=MinSizeRel
-else
-    cd build-emscripten
-fi
-emmake make -j20
-emmake make install
+        # apply config patches for emscripte
+        set +e
+        patch_out=$(patch --forward -d "$PSON_DIR" -p1 -i "$BASE_DIR/patches/pson-cpp.patch")
+        status=$?
+        if [ $status -eq 1 ]; then
+            if [[ $patch_out == *"FAILED"* ]]; then
+                echo "Patching PSON FAILED"; exit -1;
+            fi
+        fi
+        set -e
+
+        if [ ! -d "./build-emscripten" ]; then
+            mkdir -p build-emscripten && cd build-emscripten
+            emcmake cmake .. -D CMAKE_BUILD_TYPE=MinSizeRel
+        else
+            cd build-emscripten
+        fi
+        emmake make -j20
+        emmake make install
+
+        set +e
+        $SCRIPT_PATH/check_dir_checksum "$PSON_DIR"
+        set -e
+        ;;
+    2)
+        echo "\n\n\nBłąd wejścia" >&2
+        exit 2
+        ;;
+    *)
+        echo "\n\n\nNieznany kod wyjścia: $RESULT" >&2
+        exit 3
+        ;;
+esac
+
