Update build_privmx_endpoint

diff --git a/scripts/build_privmx_endpoint b/scripts/build_privmx_endpoint
--- a/scripts/build_privmx_endpoint
+++ b/scripts/build_privmx_endpoint
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 set -e
 SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
 if [ -z "$1" ]; then
@@ -12,32 +13,67 @@ source "$EMSDK_DIR/emsdk_env.sh"
 
 PRIVMX_ENDPOINT_DIR="$SOURCE_DIR/privmx-endpoint-$VERSION"
 
-if [ -d "$PRIVMX_ENDPOINT_DIR" ];
-then
+if [ -d "$PRIVMX_ENDPOINT_DIR" ]; then
     echo "$PRIVMX_ENDPOINT_DIR directory exists. Skip download of sources."
 else
-	echo "$PRIVMX_ENDPOINT_DIR directory does not exist. Get sources..."
+    echo "$PRIVMX_ENDPOINT_DIR directory does not exist. Get sources..."
+
+    RELEASE_EXISTS=$(curl -s -H "Accept: application/vnd.github+json" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/repos/simplito/privmx-endpoint/releases | jq -r '.[].tag_name' | grep -x "$VERSION" || true)
 
     ZIP_TMP_DIR=$(mktemp -d)
     OUT_TMP_DIR=$(mktemp -d)
-    curl -L \
-    -H "Accept: application/vnd.github+json" \
-    -H "X-GitHub-Api-Version: 2022-11-28" \
-    https://api.github.com/repos/simplito/privmx-endpoint/zipball/$VERSION -o $ZIP_TMP_DIR/$VERSION.zip
 
-    unzip "$ZIP_TMP_DIR/$VERSION.zip" -d $OUT_TMP_DIR
-    rm -rf $ZIP_TMP_DIR
-    cd $OUT_TMP_DIR
-    ZIP_INNER_DIR=`ls`
-    mv $ZIP_INNER_DIR $PRIVMX_ENDPOINT_DIR
-    cd "$SOURCE_DIR"
-    rm -rf $OUT_TMP_DIR
+    if [ -n "$RELEASE_EXISTS" ]; then
+        echo "Release $VERSION found. Downloading release zip..."
+        curl -L \
+        -H "Accept: application/vnd.github+json" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/repos/simplito/privmx-endpoint/zipball/$VERSION -o "$ZIP_TMP_DIR/$VERSION.zip"
+
+        unzip "$ZIP_TMP_DIR/$VERSION.zip" -d "$OUT_TMP_DIR"
+        rm -rf "$ZIP_TMP_DIR"
+        cd "$OUT_TMP_DIR"
+        ZIP_INNER_DIR=$(ls)
+        mv "$ZIP_INNER_DIR" "$PRIVMX_ENDPOINT_DIR"
+        cd "$SOURCE_DIR"
+        rm -rf "$OUT_TMP_DIR"
+    else
+        echo "Release $VERSION not found. Trying to checkout branch/commit/tag $VERSION..."
+        git clone https://github.com/simplito/privmx-endpoint.git $OUT_TMP_DIR
+        cd "$OUT_TMP_DIR"
+
+        git fetch --all --tags >/dev/null 2>&1
+        if git show-ref --verify --quiet "refs/heads/$VERSION"; then
+            git checkout "$VERSION"
+            echo "Checked out local branch $VERSION."
+        elif git ls-remote --heads origin "$VERSION" | grep -q "$VERSION"; then
+            git checkout -b "$VERSION" "origin/$VERSION"
+            echo "Checked out remote branch $VERSION."
+        elif git rev-parse --verify "refs/tags/$VERSION" >/dev/null 2>&1; then
+            git checkout "tags/$VERSION"
+            echo "Checked out tag $VERSION (detached HEAD)."
+        elif git rev-parse --verify "$VERSION" >/dev/null 2>&1; then
+            git checkout "$VERSION"
+            echo "Checked out commit $VERSION (detached HEAD)."
+
+        else
+            echo "Error: $VERSION is not a branch, tag, or commit."
+            exit 1
+        fi
+        
+        mv "$OUT_TMP_DIR" "$PRIVMX_ENDPOINT_DIR"
+        cd "$SOURCE_DIR"
+        rm -rf "$OUT_TMP_DIR"
+    fi
 fi
 
 cd "$PRIVMX_ENDPOINT_DIR"
 
+rm -rf ./build-emscripten
 mkdir -p build-emscripten && cd build-emscripten
-emcmake cmake .. -D PRIVMX_EMSCRIPTEN=ON -D PRIVMX_BUILD_ENDPOINT=ON -D PRIVMX_DRIVER_CRYPTO=ON -D PRIVMX_DRIVER_NET=ON \
+emcmake cmake .. -D PRIVMX_EXECUTOR_THREAD_POOL_SIZE=2 -D PRIVMX_EMSCRIPTEN=ON -D PRIVMX_BUILD_ENDPOINT=ON -D PRIVMX_DRIVER_CRYPTO=ON -D PRIVMX_DRIVER_NET=ON \
     -D CMAKE_BUILD_TYPE=MinSizeRel 
 emmake make -j20
 emmake make install
